import { CpuChipIcon, LightBulbIcon, WrenchScrewdriverIcon } from "@heroicons/react/24/outline";
import { Button, CheckList, FinalCTA, PageHeader } from "@/components/ui";
import { pageMetadata } from "@/lib/metadata";

export const metadata = pageMetadata("Consulting Services", "Explore Lisa Silva’s AI clarity, operational consulting, and product and environment innovation services.", "/services");

const aiServices = ["Signal Audit™","Signal Audit™ — Bulk Mode","Schema Intelligence","Website Trust & Readiness Review","Local Intent & Freshness Engine","AuditVoice™","Persona Engine","Agency Intelligence Dashboard™","Quote Calculator"];
const operationServices = ["Inventory systems","Ordering systems","Workflow automation","Chatbot automation","Documentation clarity audits","Fraud-awareness audits","Customer experience redesign","Office automation","Environment design"];
const innovationAreas = ["Teacup Chihuahua lifestyle line","Carriers that attach to carts, cars & bikes","Foldable shopping carts","Bubble umbrellas","Apartment kennel architecture","Teacup dog parks","Pet enrichment spaces","Retail experience tools"];

function DivisionIntro({ number, icon:Icon, title, tagline, copy }: {number:string; icon:typeof CpuChipIcon; title:string; tagline:string; copy:string}) { return <div className="grid gap-7 lg:grid-cols-[.65fr_1.35fr]"><div><span className="text-xs font-bold tracking-[.2em] text-gold">DIVISION {number}</span><Icon className="mt-8 h-10 w-10 text-teal"/></div><div><h2 className="font-display text-4xl sm:text-5xl">{title}</h2><p className="mt-3 text-lg font-bold text-teal">{tagline}</p><p className="mt-5 max-w-2xl leading-8 text-charcoal/65">{copy}</p></div></div> }

export default function ServicesPage(){return <>
  <PageHeader eyebrow="Consulting services" title="Clarity can take more than one shape." copy="Sometimes you need to understand how AI sees your business. Sometimes your team needs a better workflow. Sometimes the solution is a product or place no one has built yet."><Button href="/contact">Find the right starting point</Button></PageHeader>
  <section id="ai-clarity" className="section-pad scroll-mt-24"><div className="container-site"><DivisionIntro number="01" icon={CpuChipIcon} title="AI Clarity Consulting / AgentAirDirect" tagline="Control How AI Describes Your Business." copy="Understand the signals AI systems use to interpret your business, identify the gaps, and build a more complete, trustworthy picture." />
    <div className="mt-12 grid gap-5 lg:grid-cols-[1.25fr_.75fr]"><div className="card p-7 sm:p-9"><h3 className="font-display text-3xl">Services</h3><div className="mt-7 grid gap-x-8 gap-y-3 sm:grid-cols-2"><CheckList items={aiServices.slice(0,5)}/><CheckList items={aiServices.slice(5)}/></div></div><aside className="rounded-3xl bg-teal p-7 text-white sm:p-9"><p className="text-xs font-bold uppercase tracking-[.18em] text-gold-light">Starting investment</p><p className="mt-6 font-display text-5xl">$1,500</p><p className="mt-2 font-bold">Signal Audit™</p><p className="mt-5 text-sm leading-6 text-white/65">Add-ons and expanded intelligence tools are priced per project.</p><Button href="/agentairdirect" variant="secondary" className="mt-7">View AgentAirDirect</Button></aside></div>
  </div></section>
  <section id="operations" className="section-pad scroll-mt-24 border-y border-teal/10 bg-white/55"><div className="container-site"><DivisionIntro number="02" icon={WrenchScrewdriverIcon} title="Operational Consulting" tagline="Fix unclear operations, workflows, and documentation." copy="I look at how the work actually happens, where time and trust are being lost, and what kind of system would make the day easier." />
    <div className="mt-12 grid gap-5 lg:grid-cols-2"><div className="card p-7 sm:p-9"><h3 className="font-display text-3xl">What I can improve</h3><div className="mt-7 grid gap-x-8 gap-y-3 sm:grid-cols-2"><CheckList items={operationServices.slice(0,5)}/><CheckList items={operationServices.slice(5)}/></div></div><div className="rounded-3xl bg-gold-light/45 p-7 sm:p-9"><h3 className="font-display text-3xl">Businesses I understand</h3><div className="mt-6 flex flex-wrap gap-2">{["Restaurants","Apartment complexes","Retail stores","Small businesses","Healthcare-adjacent offices","Gig-economy dependent businesses","Hispanic-owned businesses"].map(x=><span key={x} className="rounded-full bg-white/80 px-4 py-2 text-xs font-bold text-charcoal/70">{x}</span>)}</div><div className="mt-9 border-t border-gold/20 pt-7"><p className="text-xs font-bold uppercase tracking-[.18em] text-gold">Project range</p><p className="mt-2 font-display text-4xl">$1,500–$5,000</p><p className="mt-2 text-sm text-charcoal/60">Scope and implementation needs determine the final investment.</p></div></div></div>
  </div></section>
  <section id="innovation" className="section-pad scroll-mt-24"><div className="container-site"><DivisionIntro number="03" icon={LightBulbIcon} title="Product & Environment Innovation" tagline="I invent solutions to real problems." copy="The best ideas often begin with a small daily frustration. I develop those observations into products, spaces, and adaptable systems with real-world potential." />
    <div className="mt-12 grid gap-5 lg:grid-cols-[.9fr_1.1fr]"><div className="rounded-3xl bg-teal p-7 text-white sm:p-9"><h3 className="font-display text-3xl">Innovation areas</h3><div className="mt-7"><CheckList items={innovationAreas} light/></div></div><div className="card p-7 sm:p-9"><h3 className="font-display text-3xl">Ways to collaborate</h3><div className="mt-7 grid gap-3 sm:grid-cols-2">{["Product design","Prototype development","Licensing","Manufacturing partnerships","Retail partnerships"].map((x,i)=><div key={x} className="rounded-2xl border border-teal/10 bg-ivory p-5"><span className="text-xs font-bold text-gold">0{i+1}</span><p className="mt-3 font-bold">{x}</p></div>)}</div><div className="mt-8 border-t border-teal/10 pt-6"><p className="text-xs font-bold uppercase tracking-[.18em] text-teal">Investment</p><p className="mt-2 font-display text-4xl">Custom</p><p className="mt-2 text-sm text-charcoal/60">Structured around concept stage, development needs, and partnership model.</p></div></div></div>
  </div></section>
  <FinalCTA title="Which kind of clarity do you need?" copy="You don’t have to choose the perfect service before reaching out. Tell me what’s happening, and I’ll help identify the most useful starting point." />
  </>}
