import { ArrowPathIcon, ChartBarSquareIcon, CheckBadgeIcon, CircleStackIcon, EyeIcon, MagnifyingGlassIcon, SignalIcon, SparklesIcon } from "@heroicons/react/24/outline";
import { Button, CheckList, FinalCTA, NumberBadge, SectionHeading } from "@/components/ui";
import { pageMetadata } from "@/lib/metadata";

export const metadata = pageMetadata("AgentAirDirect", "Control how AI describes your business with AgentAirDirect Signal Audit™, schema intelligence, and AI clarity services.", "/agentairdirect");

const services = [
  [SignalIcon,"Signal Audit™","See how leading AI systems describe your business, where they disagree, and what important signals are missing."],
  [CircleStackIcon,"Schema Intelligence","Turn your business facts into structured, machine-readable signals AI systems can understand with more confidence."],
  [CheckBadgeIcon,"Trust & Readiness Review","Assess whether your website gives people and AI enough evidence to understand, verify, and trust your business."],
  [ArrowPathIcon,"Local Intent & Freshness Engine","Keep location, service, and recency signals accurate so your business stays relevant to real customer questions."],
  [SparklesIcon,"AuditVoice™ + Persona Engine","Translate findings into clear language and see how different customer perspectives change the questions being asked."],
  [ChartBarSquareIcon,"Agency Intelligence Dashboard™","Manage patterns, priorities, and opportunities across multiple clients or locations from one intelligence view."],
] as const;

const faqs = [
  ["Is this SEO?","Not exactly. SEO is one part of your public signal. A Signal Audit™ looks more broadly at how AI systems interpret your business across your website, structured data, trust indicators, location context, freshness, and the consistency of your online story."],
  ["What do I receive?","You receive a clear, human-readable report showing what AI currently understands, where the story breaks down, which signals matter most, and a prioritized plan for improving them."],
  ["Do you make the recommended changes?","Implementation can be added to your project. Depending on the findings, that may include schema, website clarity, trust content, local signals, or an ongoing freshness system."],
  ["Is this useful for agencies or multi-location brands?","Yes. Bulk Mode and the Agency Intelligence Dashboard™ are designed to reveal patterns and priorities across larger sets of businesses or locations."],
  ["How long does an audit take?","Timing depends on the size and complexity of your business footprint. Your project scope and delivery date will be confirmed before work begins."],
];

export default function AgentAirDirectPage(){return <>
  <div className="bg-teal-dark text-white">
    <section className="relative overflow-hidden pt-28 sm:pt-36"><div className="absolute inset-0 opacity-15 noise-grid"/><div className="absolute -right-32 top-10 h-[520px] w-[520px] rounded-full border-[90px] border-white/5"/><div className="container-site relative grid gap-12 py-20 lg:grid-cols-[1.1fr_.9fr] lg:items-center lg:py-28"><div><p className="mb-5 text-xs font-bold uppercase tracking-[.22em] text-gold-light">Lisa Silva presents · AgentAirDirect</p><h1 className="font-display text-6xl leading-[.9] sm:text-7xl lg:text-[5.8rem]">Control How AI <span className="italic text-gold-light">Describes</span> Your Business.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-white/70">AI is already answering questions about your business. AgentAirDirect helps you see the story it is telling—and gives you a practical system for making that story clearer, more accurate, and easier to trust.</p><div className="mt-9 flex flex-wrap gap-3"><Button href="/contact?service=signal-audit" variant="secondary">Request a Signal Audit™</Button><Button href="#how-it-works" className="border-white/20 bg-white/10 text-white hover:bg-white/20">See how it works</Button></div></div>
      <div className="relative mx-auto aspect-square w-full max-w-md"><div className="absolute inset-0 rounded-full border border-white/10"/><div className="absolute inset-[13%] rounded-full border border-dashed border-gold/40"/><div className="absolute inset-[27%] flex items-center justify-center rounded-full bg-white/10 backdrop-blur-md"><div className="text-center"><EyeIcon className="mx-auto h-11 w-11 text-gold-light"/><p className="mt-3 text-xs font-bold uppercase tracking-[.16em]">Your AI signal</p></div></div>{["Clear","Trusted","Current","Consistent"].map((x,i)=><span key={x} className={`absolute rounded-full border border-white/10 bg-white/10 px-4 py-2 text-xs font-bold backdrop-blur-md ${i===0?"left-0 top-[26%]":i===1?"right-0 top-[20%]":i===2?"bottom-[20%] right-0":"bottom-[15%] left-[5%]"}`}>{x}</span>)}</div>
    </div></section>
    <div className="border-y border-white/10"><div className="container-site grid divide-y divide-white/10 sm:grid-cols-3 sm:divide-x sm:divide-y-0">{[["01","See the current story"],["02","Find the signal gaps"],["03","Build greater clarity"]].map(([n,t])=><div key={n} className="flex items-center gap-4 py-6 sm:px-6 first:pl-0"><span className="text-xs font-bold text-gold-light">{n}</span><p className="text-sm font-semibold text-white/75">{t}</p></div>)}</div></div>
  </div>
  <section className="section-pad"><div className="container-site grid gap-12 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><SectionHeading eyebrow="What it solves" title="Your business has an AI reputation—whether you manage it or not." copy="AI systems piece together answers from scattered signals. When those signals are thin, inconsistent, outdated, or hard to verify, the resulting picture can be incomplete or simply wrong." /></div><div className="grid gap-3 sm:grid-cols-2">{["AI gives vague or inaccurate answers","Services and specialties get overlooked","Location context is incomplete","Trust signals are hard to verify","Old information competes with current facts","Your strongest differentiators stay invisible"].map((x,i)=><div key={x} className="card flex items-start gap-3 p-5"><span className="mt-1 h-2.5 w-2.5 shrink-0 rounded-full bg-gold"/><p className="text-sm font-semibold leading-6 text-charcoal/70">{x}</p></div>)}</div></div></section>
  <section id="how-it-works" className="section-pad scroll-mt-24 bg-[#F2EEE5]"><div className="container-site"><SectionHeading eyebrow="The Signal Audit™" title="A clear view of what AI sees." copy="The audit turns an invisible interpretation problem into a focused, useful plan." align="center"/><div className="mx-auto mt-14 grid max-w-6xl gap-5 lg:grid-cols-4">{[
    ["01",MagnifyingGlassIcon,"Observe","We ask realistic questions across relevant AI systems and document the answers your customers may encounter."],
    ["02",EyeIcon,"Compare","We compare what AI says with what is true, important, distinctive, and current about your business."],
    ["03",SignalIcon,"Diagnose","We trace weak or conflicting answers back to missing, unclear, or inconsistent source signals."],
    ["04",ChartBarSquareIcon,"Prioritize","You receive an ordered roadmap showing what to fix first and why it matters."],
  ].map(([n,Icon,t,c])=>{const I=Icon as typeof EyeIcon;return <article key={n as string} className="card p-6"><div className="flex items-center justify-between"><NumberBadge>{n as string}</NumberBadge><I className="h-6 w-6 text-teal/50"/></div><h3 className="mt-8 font-display text-2xl">{t as string}</h3><p className="mt-3 text-sm leading-7 text-charcoal/65">{c as string}</p></article>})}</div></div></section>
  <section className="section-pad"><div className="container-site"><SectionHeading eyebrow="The clarity toolkit" title="Go from audit to action." copy="Start with a Signal Audit™, then add the intelligence and implementation your business actually needs."/><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{services.map(([Icon,t,c])=><article key={t} className="card group p-7 transition-transform hover:-translate-y-1"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-teal-light text-teal"><Icon className="h-6 w-6"/></span><h3 className="mt-8 font-display text-2xl">{t}</h3><p className="mt-4 text-sm leading-7 text-charcoal/65">{c}</p></article>)}</div></div></section>
  <section className="section-pad bg-teal text-white"><div className="container-site grid gap-12 lg:grid-cols-[1fr_.8fr] lg:items-center"><div><p className="mb-4 text-xs font-bold uppercase tracking-[.2em] text-gold-light">Pricing</p><h2 className="font-display text-5xl sm:text-6xl">Start with the signal.</h2><p className="mt-6 max-w-xl leading-8 text-white/70">The Signal Audit™ gives you the foundation: a clear view of how AI understands your business and a prioritized path forward.</p><div className="mt-8"><CheckList light items={["Multi-system AI perception review","Signal gap and inconsistency analysis","Clear, human-readable findings","Prioritized recommendations"]}/></div></div><div className="rounded-4xl border border-white/15 bg-white/10 p-8 backdrop-blur-sm sm:p-10"><p className="text-xs font-bold uppercase tracking-[.18em] text-gold-light">Signal Audit™</p><p className="mt-6 font-display text-6xl">$1,500</p><p className="mt-4 text-sm leading-6 text-white/60">Add-ons, implementation, Bulk Mode, and agency intelligence tools are scoped and priced per project.</p><Button href="/contact?service=signal-audit" variant="secondary" className="mt-8 w-full">Request your audit</Button></div></div></section>
  <section className="section-pad"><div className="container-site grid gap-12 lg:grid-cols-[.65fr_1.35fr]"><SectionHeading eyebrow="Frequently asked" title="Good questions, clear answers."/><div className="divide-y divide-teal/10 border-y border-teal/10">{faqs.map(([q,a])=><details key={q} className="group py-6"><summary className="flex cursor-pointer list-none items-center justify-between gap-5 font-display text-xl sm:text-2xl">{q}<span className="text-2xl font-light text-teal transition-transform group-open:rotate-45">+</span></summary><p className="mt-4 max-w-2xl pr-8 text-sm leading-7 text-charcoal/65">{a}</p></details>)}</div></div></section>
  <FinalCTA title="Ready to see what AI sees?" copy="Request a Signal Audit™ and turn your business’s scattered online signals into a clearer, more trustworthy story."/>
  </>}
