import type { Metadata } from "next";
import { EyeIcon, HeartIcon, LightBulbIcon, SquaresPlusIcon } from "@heroicons/react/24/outline";
import { Button, FinalCTA, PageHeader, SectionHeading } from "@/components/ui";
import { Card, Stagger } from "@/components/primitives";

export const metadata: Metadata = { title: "About Lisa", description: "Meet Lisa Silva, a business systems consultant who turns unclear information, operations, and experiences into practical solutions." };

export default function AboutPage() {
  return <>
    <PageHeader eyebrow="About Lisa" title="I’m a problem solver who sees systems everywhere." copy="Not because everything needs to be complicated—but because the parts of a problem usually make more sense when you can see how they connect."><Button href="/contact">Work with me</Button></PageHeader>
    <section className="section-pad"><div className="container-site grid gap-12 lg:grid-cols-[.85fr_1.15fr] lg:items-start">
      <div className="relative min-h-[460px] overflow-hidden rounded-4xl bg-teal p-8 text-white shadow-soft sm:p-10"><div className="absolute inset-0 opacity-20 noise-grid"/><div className="absolute -bottom-24 -right-24 h-72 w-72 rounded-full border-[45px] border-gold/25"/><div className="relative flex h-full flex-col justify-between"><span className="font-display text-5xl italic text-gold-light">LS</span><blockquote className="mt-28 font-display text-3xl leading-tight sm:text-4xl">“Clarity isn’t about making things simple. It’s about making them make sense.”</blockquote><p className="mt-7 text-sm text-white/60">Lisa Silva · Business Systems Consultant</p></div></div>
      <div><p className="eyebrow">My story</p><h2 className="font-display text-4xl leading-tight sm:text-5xl">I’ve always noticed the thing behind the thing.</h2><div className="mt-7 space-y-5 text-base leading-8 text-charcoal/70"><p>I notice when customers have to ask the same question over and over. When a team has quietly created five workarounds for one broken process. When a website says the right words but still leaves people—or AI—unsure what a business really does.</p><p>That way of seeing has taken me across restaurants, apartment communities, office operations, AI visibility, customer experience, product concepts, and physical environments. The industries change. The core work doesn’t: observe closely, understand the whole system, and build something that fits real life.</p><p>I founded AgentAirDirect after recognizing a new kind of clarity problem. Businesses were being interpreted by AI systems they couldn’t see or control. They needed a practical way to understand the story their signals were telling—and how to improve it.</p><p>But I don’t think of myself as a “tech founder.” I’m a problem solver. Technology is one tool. Sometimes the better answer is a checklist, a redesigned space, a clearer sentence, a different sequence, or a product that should have existed all along.</p></div></div>
    </div></section>
    <section className="section-pad border-y border-teal/10 bg-white/50"><div className="container-site"><SectionHeading eyebrow="My philosophy" title="The best solution respects the people inside it." copy="A system can be clever and still fail. My standard is more practical: does it reduce confusion, help people make good decisions, and hold up in the real world?" /><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[
      [EyeIcon,"Observe first","The details people dismiss often explain the whole problem."],
      [SquaresPlusIcon,"Connect the pieces","Online, in-person, operational, and environmental signals influence each other."],
      [HeartIcon,"Design for humans","The solution has to make sense to the person using it on a busy Tuesday."],
      [LightBulbIcon,"Stay open","The right answer may live outside the expected category."],
    ].map(([Icon,title,copy]) => { const I = Icon as typeof EyeIcon; return <Card key={title as string} className="p-7"><I className="h-7 w-7 text-teal"/><h3 className="mt-9 font-display text-2xl">{title as string}</h3><p className="mt-4 text-sm leading-7 text-charcoal/60">{copy as string}</p></Card>})}</Stagger></div></section>
    <section className="section-pad"><div className="container-site grid gap-12 lg:grid-cols-2 lg:items-center"><div><SectionHeading eyebrow="Multi-domain expertise" title="I work across boundaries because businesses do, too." copy="Customer experience affects operations. Physical environments affect behavior. Documentation affects trust. AI visibility depends on signals across the entire business." /><p className="mt-5 leading-8 text-charcoal/70">My role is to hold that larger picture without losing the useful details. I bring systems thinking, creative invention, operational experience, and an intuitive read of human behavior to the same table.</p></div><div className="grid grid-cols-2 gap-3">{["AI & information clarity","Operations & workflows","Documentation","Customer experience","Product concepts","Physical environments","Automation","Trust & communication"].map((x,i)=><div key={x} className={`rounded-2xl p-5 text-sm font-bold ${i%3===0?"bg-teal text-white":i%3===1?"bg-gold-light/70":"border border-teal/10 bg-white"}`}>{x}</div>)}</div></div></section>
    <section className="pb-10"><div className="container-site"><div className="rounded-4xl border border-gold/20 bg-gold-light/35 p-8 sm:p-12"><p className="eyebrow">What working together feels like</p><div className="grid gap-8 lg:grid-cols-[1fr_1.2fr]"><h2 className="font-display text-4xl sm:text-5xl">Curious, direct, and refreshingly practical.</h2><p className="leading-8 text-charcoal/70">You don’t have to arrive with a tidy brief or the right vocabulary. Tell me what feels off. Show me how the work really happens. I’ll ask questions, notice patterns, and help turn a blurry problem into a decision you can act on.</p></div></div></div></section>
    <FinalCTA title="Bring me the problem you can’t quite name." />
  </>;
}
